name: flutter_system_action
description: A Flutter package for access system action button.
version: 1.0.1
homepage: https://github.com/goswamijay/flutter_system_action

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_system_action.flutter_system_action
        pluginClass: FlutterSystemActionPlugin
